spring:
  application:
    name: movie-randomizer
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.user}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?serverTimezone=America/Sao_Paulo&authSource=admin
      host: ${MONGODB_HOST:localhost}
      port: 27017
      user: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:root}
      database: movie-randomizer
      auto-index-creation: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D& ]{ @Vr?G;2?XhbC:Qa#9#eMLN\ }x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
  expiration: 99999999

minio:
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:admin123}
  endpoint: ${MINIO_ENDPOINT:http://34.201.120.115:9000}
  bucket: movie-covers
