name: Mutation Testing

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]
  push:
    branches: [ main ]
jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile and test
        run: mvn clean compile test-compile

      - name: Run PIT Mutation Coverage
        run: mvn org.pitest:pitest-maven:mutationCoverage -DwithHistory

      - name: Create mutation badge
        run: |
          MUTATION_FILE=$(find target/pit-reports -name "mutations.xml" | head -n1)
          if [ -f "$MUTATION_FILE" ]; then
            MUTATION=$(grep -oP '(?<=<mutationCoverage>)[0-9]+(?=%</mutationCoverage>)' "$MUTATION_FILE" | head -n1)
            echo "mutation=${MUTATION}" >> $GITHUB_ENV
          else
            echo "mutation=0" >> $GITHUB_ENV
          fi

      - name: Generate badge
        uses: emibcn/badge-action@v2
        with:
          label: mutation
          status: ${{ env.mutation }}%
          color: ${{ env.mutation >= 80 && 'brightgreen' || (env.mutation >= 60 && 'yellow' || 'red') }}
          path: pit-mutation-badge.svg

      - name: Upload mutation report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: target/pit-reports/

      - name: Check mutation coverage
        run: |
          if [ "${MUTATION}" -lt 90 ]; then
            echo "Mutation coverage below 90%! Failing."
            exit 1
          fi